name: "Quarkus ecosystem CI"
on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  quarkus-main:
    name: "Build against latest Quarkus main snapshot"
    if: github.actor == 'quarkusbot' || github.event_name == 'workflow_dispatch'
    uses: quarkusio/.github/.github/workflows/quarkus-ecosystem-ci.yml@main
    with:
      ecosystem_ci_repo_path: vaadin
      java_version: 21
      quarkus_version_pom_property: quarkus.version
    secrets: inherit
