name: "Quarkus ecosystem CI"
on:
  watch:
    types: [started]
  workflow_dispatch:

  # For this CI to work, ECOSYSTEM_CI_TOKEN needs to contain a GitHub with rights to close the Quarkus issue that the user/bot has opened,
  # while 'ECOSYSTEM_CI_REPO_PATH' needs to be set to the corresponding path in the 'quarkusio/quarkus-ecosystem-ci' repository

env:
  ECOSYSTEM_CI_REPO: quarkusio/quarkus-ecosystem-ci
  ECOSYSTEM_CI_REPO_FILE: context.yaml
  JAVA_VERSION: 17

  #########################
  # Repo specific setting #
  #########################

  ECOSYSTEM_CI_REPO_PATH: vaadin

  # The setup-and-test script assumes the property within pom.xml that determines the
  # quarkus version is called "quarkus.version".
  # Use this env var to override the property to something else
  # (like "quarkus.platform.version" for example)
  QUARKUS_VERSION_POM_PROPERTY: quarkus.version

jobs:
  quarkus-main:
    name: "Build against latest Quarkus snapshot"
    runs-on: ubuntu-latest
    if: github.actor == 'quarkusbot' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Install yq
        uses: dcarbone/install-yq-action@v1.0.1

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: current-repo

      - name: Checkout Ecosystem
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ECOSYSTEM_CI_REPO }}
          path: ecosystem-ci

      - name: Set TB License
        run: |
          TB_LICENSE=${{secrets.TB_LICENSE}}
          mkdir -p ~/.vaadin/
          echo '{"username":"'`echo $TB_LICENSE | cut -d / -f1`'","proKey":"'`echo $TB_LICENSE | cut -d / -f2`'"}' > ~/.vaadin/proKey

      - name: Setup and Run Tests
        run: ./ecosystem-ci/setup-and-test
        env:
          ECOSYSTEM_CI_TOKEN: ${{ secrets.ECOSYSTEM_CI_TOKEN }}
